export const TEACHER_CREATE_REQUEST = 'TEACHER_CREATE_REQUEST'
export const TEACHER_CREATE_SUCCESS = 'TEACHER_CREATE_SUCCESS'
export const TEACHER_CREATE_FAIL = 'TEACHER_CREATE_FAIL'

export const TEACHER_LIST_REQUEST = 'TEACHER_LIST_REQUEST'
export const TEACHER_LIST_SUCCESS = 'TEACHER_LIST_SUCCESS'
export const TEACHER_LIST_FAIL = 'TEACHER_LIST_FAIL'
export const TEACHER_LIST_RESET = 'TEACHER_LIST_RESET'


export const TEACHER_DELETE_REQUEST = 'TEACHER_DELETE_REQUEST'
export const TEACHER_DELETE_SUCCESS = 'TEACHER_DELETE_SUCCESS'
export const TEACHER_DELETE_FAIL = 'TEACHER_DELETE_FAIL'


